version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 15
    cooldown:
      default-days: 14
      semver-major-days: 14
      semver-minor-days: 7
      semver-patch-days: 3
    ignore:
      - dependency-name: org.keycloak.bom:*
        versions:
          - ">= 26.4"
      - dependency-name: org.keycloak:*
        versions:
          - ">= 26.4"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 15
    cooldown:
      default-days: 14

  - package-ecosystem: docker
    directory: /src/main/docker-initContainer/
    schedule:
      interval: daily
    cooldown:
      default-days: 14
